touch signup.in.txt && echo salam > signup.in.txt
touch signup.out.txt && echo salam > signup.out.txt
touch login.in.txt && echo salam > login.in.txt
touch login.out.txt && echo salam > login.out.txt
touch addFilm.in.txt && echo salam > addFilm.in.txt
touch addFilm.out.txt && echo salam > addFilm.out.txt
touch editFilm.in.txt && echo salam > editFilm.in.txt
touch editFilm.out.txt && echo salam > editFilm.out.txt
touch deleteFilm.in.txt && echo salam > deleteFilm.in.txt
touch deleteFilm.out.txt && echo salam > deleteFilm.out.txt
touch getFilms.in.txt && echo salam > getFilms.in.txt
touch getFilms.out.txt && echo salam > getFilms.out.txt
touch filmDetails.in.txt && echo salam > filmDetails.in.txt
touch filmDetails.out.txt && echo salam > filmDetails.out.txt
touch commentReply.in.txt && echo salam > commentReply.in.txt
touch commentReply.out.txt && echo salam > commentReply.out.txt
touch commentDelete.in.txt && echo salam > commentDelete.in.txt
touch commentDelete.out.txt && echo salam > commentDelete.out.txt
touch publisherFollowers.in.txt && echo salam > publisherFollowers.in.txt
touch publisherFollowers.out.txt && echo salam > publisherFollowers.out.txt
touch getMoney.in.txt && echo salam > getMoney.in.txt
touch getMoney.out.txt && echo salam > getMoney.out.txt
