touch signup.in.txt && echo signup > signup.in.txt
touch signup.out.txt && echo signup > signup.out.txt
touch login.in.txt && echo login > login.in.txt
touch login.out.txt && echo login > login.out.txt
touch addFilm.in.txt && echo addFilm > addFilm.in.txt
touch addFilm.out.txt && echo addFilm > addFilm.out.txt
touch editFilm.in.txt && echo editFilm > editFilm.in.txt
touch editFilm.out.txt && echo editFilm > editFilm.out.txt
touch deleteFilm.in.txt && echo deleteFilm > deleteFilm.in.txt
touch deleteFilm.out.txt && echo deleteFilm > deleteFilm.out.txt
touch getFilms.in.txt && echo getFilms > getFilms.in.txt
touch getFilms.out.txt && echo getFilms > getFilms.out.txt
touch filmDetails.in.txt && echo filmDetails > filmDetails.in.txt
touch filmDetails.out.txt && echo filmDetails > filmDetails.out.txt
touch commentReply.in.txt && echo commentReply > commentReply.in.txt
touch commentReply.out.txt && echo commentReply > commentReply.out.txt
touch commentDelete.in.txt && echo commentDelete > commentDelete.in.txt
touch commentDelete.out.txt && echo commentDelete > commentDelete.out.txt
touch publisherFollowers.in.txt && echo publisherFollowers > publisherFollowers.in.txt
touch publisherFollowers.out.txt && echo publisherFollowers > publisherFollowers.out.txt
touch getMoney.in.txt && echo getMoney > getMoney.in.txt
touch getMoney.out.txt && echo getMoney > getMoney.out.txt
touch customerFollow.in.txt && echo customerFollow > customerFollow.in.txt
touch customerFollow.out.txt && echo customerFollow > customerFollow.out.txt
touch customerMoney.in.txt && echo customerMoney > customerMoney.in.txt
touch customerMoney.out.txt && echo customerMoney > customerMoney.out.txt
touch search.in.txt && echo search > search.in.txt
touch search.out.txt && echo search > search.out.txt
touch customerFilmDetails.in.txt && echo customerFilmDetails > customerFilmDetails.in.txt
touch customerFilmDetails.out.txt && echo customerFilmDetails > customerFilmDetails.out.txt
touch buyFilm.in.txt && echo buyFilm > buyFilm.in.txt
touch buyFilm.out.txt && echo buyFilm > buyFilm.out.txt
touch rateFilm.in.txt && echo rateFilm > rateFilm.in.txt
touch rateFilm.out.txt && echo rateFilm > rateFilm.out.txt
touch customerComment.in.txt && echo customerComment > customerComment.in.txt
touch customerComment.out.txt && echo customerComment > customerComment.out.txt
touch customerFilmList.in.txt && echo customerFilmList > customerFilmList.in.txt
touch customerFilmList.out.txt && echo customerFilmList > customerFilmList.out.txt
touch customerNotifs.in.txt && echo customerNotifs > customerNotifs.in.txt
touch customerNotifs.out.txt && echo customerNotifs > customerNotifs.out.txt
